[other]

; list title
title.fg = cyan

; status bar
statusBar.bg = blue
statusBar.fg = black

; current list title
titleCurrent.fg = magenta

; current task
taskCurrent.fg = magenta

; subtasks
; selected
subtaskCurrent.fg = magenta
; incomplete
subtaskIncomplete.fg = yellow
; complete
subtaskComplete.fg = green

; disabled
disabled.fg = brightBlue

[default]
